### ISSUE TITLE
Clone git and then gradlew installDebug fails

### ISSUE THREAD

**Issue by friedger** [ligi/AndroidNewUnitTestTest#2]
After a clean clone of the repo, running installDebug fails with the message below.

A problem was found with the configuration of task ':app:installDebug'.

> File '/usr/local/opt/android-sdk/build-tools/21.1.2/split-select' specified for property 'splitSelectExe' does not exist.

**Comment by ligi** [comment]
thanks - but the root is here: https://code.google.com/p/android/issues/detail?id=135513
